library(tidyverse)
name <- read.delim('features.txt',header=FALSE,sep=" ",stringsAsFactors = FALSE)
colid <- grep('mean(?!Freq)|std',name$V2,perl = TRUE)
colname <- grep('mean(?!Freq)|std',name$V2,perl = TRUE,value = TRUE)
testx <- read.table('test/X_test.txt',header=FALSE)
testx <- testx[,colid]
testy <- read.table('test/y_test.txt',header=FALSE)
subtest <- read.table('test/subject_test.txt',header=FALSE)
test <- cbind(subtest,testy,testx)
trainx <- read.table('train/X_train.txt',header=FALSE)
trainx <- trainx[,colid]
trainy <- read.table('train/y_train.txt',header=FALSE)
subtrain <- read.table('train/subject_train.txt',header=FALSE)
train <- cbind(subtrain,trainy,trainx)
har <- rbind(train,test)
names(har) <- c('sub','act',colname)
head(har)
har <- within(har,{act=factor(act,levels=seq(1,6),labels=c('Walking','Walking_Upstairs','Walking_Downstairs','Sitting','Standing','Laying'))})
har <- as_tibble(har)
har1 <- har%>%group_by(sub,act)
descp <- summarise_all(har1,mean)
write_csv(descp,'descp.csv')